### ISSUE TITLE
How to limit colors used

### ISSUE THREAD

**Issue by mationai** [YYsuni/blockies-react-svg#3]
Certain colors like dark red and dark green don't go together. Is there a way to limit or change the color options? If not, can you point me to the code loation where I can change that?

thank you for open sourcing this.

**Comment by YYsuni** [comment]
Yes, you can fork it and update the `/src/blockies.ts`, but if you did, it would be against native logic (https://github.com/download13/blockies)

**Comment by mationai** [comment]
k, thanks.
